"""N5 课程初始数据（蜡笔小新主题）"""

N5_LESSONS = [
    {
        "lesson_id": "n5_01",
        "level": "N5",
        "lesson_no": 1,
        "title": "冒険の始まり",
        "chapter": "开学季",
        "description": "自我介绍、数字、颜色 — しんちゃん登場！",
        "vocab_count": 6,
        "grammar_points": "〜は〜です、〜ます",
        "shinchan_line": "オラは野原しんのすけ！5歳だゾ！",
        "vocabulary": [
            {"japanese": "私", "kana": "わたし", "meaning": "我", "example": "私はしんのすけです", "example_meaning": "我是新之助", "kanji": "私"},
            {"japanese": "名前", "kana": "なまえ", "meaning": "名字", "example": "名前は何ですか", "example_meaning": "你叫什么名字？", "kanji": "名前"},
            {"japanese": "学校", "kana": "がっこう", "meaning": "学校", "example": "学校に行きます", "example_meaning": "去学校", "kanji": "学校"},
            {"japanese": "先生", "kana": "せんせい", "meaning": "老师", "example": "先生、おはよう", "example_meaning": "老师早上好", "kanji": "先生"},
            {"japanese": "友達", "kana": "ともだち", "meaning": "朋友", "example": "友達と遊びます", "example_meaning": "和朋友玩", "kanji": "友達"},
            {"japanese": "一年生", "kana": "いちねんせい", "meaning": "一年级", "example": "私は一年生です", "example_meaning": "我是一年级", "kanji": "一年生"},
        ],
    },
    {
        "lesson_id": "n5_02",
        "level": "N5",
        "lesson_no": 2,
        "title": "しんちゃんの一日",
        "chapter": "蜡笔小新的一天",
        "description": "日常用语：起床、上学、吃饭、睡觉",
        "vocab_count": 6,
        "grammar_points": "〜する、〜た（过去形）",
        "shinchan_line": "朝ご飯を食べて、幼稚園に行くんだゾ！",
        "vocabulary": [
            {"japanese": "朝", "kana": "あさ", "meaning": "早上", "example": "朝ご飯を食べます", "example_meaning": "吃早饭", "kanji": "朝"},
            {"japanese": "昼", "kana": "ひる", "meaning": "中午", "example": "昼ご飯を食べます", "example_meaning": "吃午饭", "kanji": "昼"},
            {"japanese": "夜", "kana": "よる", "meaning": "晚上", "example": "夜ご飯を食べます", "example_meaning": "吃晚饭", "kanji": "夜"},
            {"japanese": "起きる", "kana": "おきる", "meaning": "起床", "example": "朝6時に起きます", "example_meaning": "早上6点起床", "kanji": "起"},
            {"japanese": "寝る", "kana": "ねる", "meaning": "睡觉", "example": "夜9時に寝ます", "example_meaning": "晚上9点睡觉", "kanji": "寝"},
            {"japanese": "学校", "kana": "がっこう", "meaning": "去学校", "example": "学校に行きました", "example_meaning": "去了学校（过去）", "kanji": "学校"},
        ],
    },
    {
        "lesson_id": "n5_03",
        "level": "N5",
        "lesson_no": 3,
        "title": "お誕生日パーティー",
        "chapter": "生日派对",
        "description": "日期、时间、礼物、食物",
        "vocab_count": 6,
        "grammar_points": "〜が好きです、〜をください",
        "shinchan_line": "ケーキを食べたいゾ〜！",
        "vocabulary": [
            {"japanese": "誕生日", "kana": "たんじょうび", "meaning": "生日", "example": "今日は私の誕生日です", "example_meaning": "今天是我的生日", "kanji": "誕生日"},
            {"japanese": "プレゼント", "kana": "ぷれぜんと", "meaning": "礼物", "example": "プレゼントをもらいました", "example_meaning": "收到了礼物", "kanji": ""},
            {"japanese": "ケーキ", "kana": "けーき", "meaning": "蛋糕", "example": "ケーキが好きです", "example_meaning": "喜欢蛋糕", "kanji": ""},
            {"japanese": "楽しい", "kana": "たのしい", "meaning": "快乐", "example": "誕生日は楽しいです", "example_meaning": "生日很快乐", "kanji": "楽"},
            {"japanese": "嬉しい", "kana": "うれしい", "meaning": "开心", "example": "プレゼントを見て嬉しい", "example_meaning": "看到礼物很开心", "kanji": "嬉"},
            {"japanese": "欲しい", "kana": "ほしい", "meaning": "想要", "example": "新しいおもちゃが欲しい", "example_meaning": "想要新玩具", "kanji": "欲"},
        ],
    },
    {
        "lesson_id": "n5_04",
        "level": "N5",
        "lesson_no": 4,
        "title": "学校の一日",
        "chapter": "校园生活",
        "description": "教室、科目、活动",
        "vocab_count": 6,
        "grammar_points": "〜で（场所）、〜を（目的）",
        "shinchan_line": "先生！おしりを出してもいいですか？😂",
        "vocabulary": [
            {"japanese": "教室", "kana": "きょうしつ", "meaning": "教室", "example": "教室で勉強します", "example_meaning": "在教室学习", "kanji": "教室"},
            {"japanese": "本", "kana": "ほん", "meaning": "书", "example": "本を読みます", "example_meaning": "读书", "kanji": "本"},
            {"japanese": "勉強", "kana": "べんきょう", "meaning": "学习", "example": "日本語を勉強します", "example_meaning": "学习日语", "kanji": "勉強"},
            {"japanese": "絵", "kana": "え", "meaning": "画", "example": "絵を描きます", "example_meaning": "画画", "kanji": "絵"},
            {"japanese": "歌", "kana": "うた", "meaning": "歌", "example": "歌を歌います", "example_meaning": "唱歌", "kanji": "歌"},
            {"japanese": "遊ぶ", "kana": "あそぶ", "meaning": "玩", "example": "友達と遊びます", "example_meaning": "和朋友玩", "kanji": "遊"},
        ],
    },
    {
        "lesson_id": "n5_05",
        "level": "N5",
        "lesson_no": 5,
        "title": "ラーメン屋さんへ",
        "chapter": "拉面馆",
        "description": "点餐、味道、价格",
        "vocab_count": 6,
        "grammar_points": "〜をください、〜がほしい",
        "shinchan_line": "ラーメン、大盛りでお願いします！",
        "vocabulary": [
            {"japanese": "ラーメン", "kana": "らーめん", "meaning": "拉面", "example": "ラーメンが食べたい", "example_meaning": "想吃拉面", "kanji": "拉麺"},
            {"japanese": "メニュー", "kana": "めにゅー", "meaning": "菜单", "example": "メニューを見せてください", "example_meaning": "请给我看菜单", "kanji": ""},
            {"japanese": "美味しい", "kana": "おいしい", "meaning": "好吃", "example": "このラーメンは美味しい", "example_meaning": "这碗拉面好吃", "kanji": "美味"},
            {"japanese": "値段", "kana": "ねだん", "meaning": "价格", "example": "値段はいくらですか", "example_meaning": "多少钱？", "kanji": "値段"},
            {"japanese": "水", "kana": "みず", "meaning": "水", "example": "水をください", "example_meaning": "请给我水", "kanji": "水"},
            {"japanese": "お箸", "kana": "おはし", "meaning": "筷子", "example": "お箸を使います", "example_meaning": "用筷子", "kanji": "箸"},
        ],
    },
]
